export const styles = {
  body: {
    fontFamily: 'var(--vscode-font-family)',
    color: 'var(--vscode-foreground)',
    backgroundColor: 'var(--vscode-editor-background)',
    padding: '2rem',
    lineHeight: 1.6,
  },
  container: {
    maxWidth: '900px',
    margin: '0 auto',
  },
  h1: {
    fontSize: '2rem',
    marginBottom: '0.5rem',
    color: 'var(--vscode-textLink-foreground)',
  },
  subtitle: {
    fontSize: '1.1rem',
    color: 'var(--vscode-descriptionForeground)',
    marginBottom: '2rem',
  },
  section: {
    background: 'var(--vscode-editor-inactiveSelectionBackground)',
    border: '1px solid var(--vscode-panel-border)',
    borderRadius: '8px',
    padding: '1.5rem',
    marginBottom: '1.5rem',
  },
  h2: {
    fontSize: '1.3rem',
    marginBottom: '1rem',
    color: 'var(--vscode-textLink-foreground)',
  },
  p: {
    marginBottom: '1rem',
    color: 'var(--vscode-foreground)',
  },
  buttonGroup: {
    display: 'flex',
    gap: '1rem',
    flexWrap: 'wrap' as const,
    marginTop: '1rem',
  },
  button: {
    background: 'var(--vscode-button-background)',
    color: 'var(--vscode-button-foreground)',
    border: 'none',
    padding: '0.75rem 1.5rem',
    fontSize: '1rem',
    borderRadius: '4px',
    cursor: 'pointer',
    fontFamily: 'var(--vscode-font-family)',
    transition: 'background 0.2s',
  },
  buttonSecondary: {
    background: 'var(--vscode-button-secondaryBackground)',
    color: 'var(--vscode-button-secondaryForeground)',
  },
  featureGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '1rem',
    marginTop: '1rem',
  },
  featureCard: {
    background: 'var(--vscode-editor-background)',
    border: '1px solid var(--vscode-panel-border)',
    borderRadius: '6px',
    padding: '1rem',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  featureCardHover: {
    borderColor: 'var(--vscode-textLink-foreground)',
    background: 'var(--vscode-list-hoverBackground)',
  },
  featureCardH3: {
    fontSize: '1.1rem',
    marginBottom: '0.5rem',
    color: 'var(--vscode-textLink-foreground)',
  },
  featureCardP: {
    fontSize: '0.9rem',
    color: 'var(--vscode-descriptionForeground)',
    margin: 0,
  },
  badge: {
    display: 'inline-block',
    padding: '0.25rem 0.5rem',
    fontSize: '0.75rem',
    borderRadius: '3px',
    marginLeft: '0.5rem',
    background: 'var(--vscode-badge-background)',
    color: 'var(--vscode-badge-foreground)',
  },
  costBadge: {
    background: '#2ea043',
    color: 'white',
    fontWeight: 'bold' as const,
  },
  footer: {
    marginTop: '2rem',
    paddingTop: '1rem',
    borderTop: '1px solid var(--vscode-panel-border)',
    textAlign: 'center' as const,
    color: 'var(--vscode-descriptionForeground)',
    fontSize: '0.9rem',
  },
  footerLink: {
    color: 'var(--vscode-textLink-foreground)',
    textDecoration: 'none',
  },
} as const;
